SC_uint(_AlphaMaskMode, 0, [SCEnum(None, 0, Replace, 1, Multiply, 2, Add, 3, Subtract, 4)], "Alpha Mask Mode", "")
SC_Texture2D(_AlphaMask, "white", [], "Alpha Mask", "")
SC_ScaleOffset(_AlphaMask)
SC_float(_AlphaMaskScale, 1, [], "Scale", "")
SC_float(_AlphaMaskValue, 0, [], "Offset", "")
SC_Foldout(Alpha Mask 2nd)
SC_uint(_AlphaMask2ndMode, 0, [SCEnum(None, 0, Replace, 1, Multiply, 2, Add, 3, Subtract, 4)], "Alpha Mask 2nd Mode", "")
SC_Texture2D(_AlphaMask2nd, "white", [], "Alpha Mask 2nd", "")
SC_ScaleOffset(_AlphaMask2nd)
SC_float(_AlphaMask2ndScale, 1, [], "Scale", "")
SC_float(_AlphaMask2ndValue, 0, [], "Offset", "")
SC_FoldoutEnd
SC_Foldout(Alpha Mask 3rd)
SC_uint(_AlphaMask3rdMode, 0, [SCEnum(None, 0, Replace, 1, Multiply, 2, Add, 3, Subtract, 4)], "Alpha Mask 3rd Mode", "")
SC_Texture2D(_AlphaMask3rd, "white", [], "Alpha Mask 3rd", "")
SC_ScaleOffset(_AlphaMask3rd)
SC_float(_AlphaMask3rdScale, 1, [], "Scale", "")
SC_float(_AlphaMask3rdValue, 0, [], "Offset", "")
SC_FoldoutEnd
